### ISSUE TITLE
FaultExceptions thrown from UserNamePasswordValidators do not get serialised correctly

### ISSUE THREAD

**Issue by marlon-tucker** [CoreWCF/CoreWCF#676] opened 2022-05-19 16:09 UTC
Using CoreWCF version `1.0.2` 

We have a couple of custom classes that inherit from the `UserNamePasswordValidator` base class. Inside the `ValidateAsync` method we throw `FaultExceptions` to signify various authentication failures. CoreWCF does not serialise these back into a WCF response, which in our case should be a SOAP response. 

The response from AspNetCore indicates the exception is not being handled by CoreWCF so it's falling through the middleware pipeline eventually hitting the developer exception handling page, which generates a `text/plain` response.

I have double checked our NET Framework code and I have confirmed FaultExceptions thrown from `UserNamePasswordValidator` are correctly serialised.

**Comment by birojnayak** [comment] 2022-05-23 20:09
assigning to @jonlouie  we do have test https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Http/tests/SimpleWSHTTPTest.cs#L110 and we can throw exception https://github.com/CoreWCF/CoreWCF/blob/a6531a5d237e79c645fa7670b70763438139bafb/src/CoreWCF.Http/tests/SimpleWSHTTPTest.cs#L166 and see  why not getting fault exception..

**Comment by jonlouie** [comment] 2022-05-24 00:40
@birojnayak Looks like we have a negative test case where auth is set to fail: https://github.com/CoreWCF/CoreWCF/blob/a6531a5d237e79c645fa7670b70763438139bafb/src/CoreWCF.Http/tests/SimpleWSHTTPTest.cs#L77-L107

I stepped through the code and we do attempt to [return a fault SOAP message](https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Http/src/CoreWCF/Channels/AspNetCoreReplyChannel.cs#L139-L140), but I'll need to reproduce the issue to get a better understanding on where the issue is.

**Comment by marlon-tucker** [comment] 2022-05-24 15:09
That test looks like it is specifically testing the behaviour of the time out option of the binding, rather than testing exceptions thrown by the CustomUsernameValidator are getting serialised correctly.

**Comment by jonlouie** [comment] 2022-05-24 21:44
@marlon-tucker Thanks for the clarification. I wrote a new test to throw within the `UserNamePasswordValidator` class and found that the security exception was not being set, preventing a fault message reply. PR #684 addresses this, currently pending review.

**Closed** 2022-05-27 21:35 UTC
