### ISSUE TITLE
ValidateMustUnderstand property is missed in ServiceBehaviorAttribute

### ISSUE THREAD

**Issue by mikhaylo1** [CoreWCF/CoreWCF#1381] opened 2024-05-04 22:08 UTC
I am trying to port my old WCF service to CoreWCF and I have doubts about what to do with a declaration from the old service:

`[ServiceBehavior(ValidateMustUnderstand = false)]`

In CoreWCF, there is no public property for ValidateMustUnderstand, and it [appears to always be set to true](https://github.com/CoreWCF/CoreWCF/blob/a1cb5c2eee4baf607fbb287b6ac9a4c2fab97ece/src/CoreWCF.Primitives/src/CoreWCF/ServiceBehaviorAttribute.cs#L42)

**Comment by mconnew** [comment] 2024-05-07 00:00
Usually if a client has said the service must understand a specific header and it doesn't, something is wrong. Can you explain your use case, if it's a scenario I haven't considered it might make sense to add it.  

This property wasn't exposed on the ServiceBehaviorAttribute as it's intended for use as part of WCF Routing Services. With Routing Services, you aren't processing the message, just relaying it on to another service. In that situation, you don't want to reject a message because it has a header for a feature the routing service doesn't understand, because it's not the final destination for the message.  

You have two options. You could implement an IDispatchMessageInspector and in there move all headers which must be understood and weren't into Message.Headers.UnderstoodHeaders. This is basically how you say "This header was understood" marking it as a processed header.  

Alternatively, there's still a public property on DispatchRuntime so you can create your own behavior which does the equivalent thing. It would look something like this:

```c#
[AttributeUsage(AttributeTargets.Class)]
public class DisableMustUnderstandValidationAttribute : Attribute, , IServiceBehavior
{
    void IServiceBehavior.Validate(ServiceDescription description, ServiceHostBase serviceHostBase) { }
    void IServiceBehavior.AddBindingParameters(ServiceDescription serviceDescription, ServiceHostBase serviceHostBase, Collection<ServiceEndpoint> endpoints, BindingParameterCollection bindingParameters) { }
    void IServiceBehavior.ApplyDispatchBehavior(ServiceDescription description, ServiceHostBase serviceHostBase)
    {
        for (int i = 0; i < serviceHostBase.ChannelDispatchers.Count; i++)
        {
            if (serviceHostBase.ChannelDispatchers[i] is ChannelDispatcher channelDispatcher)
            {
                foreach (EndpointDispatcher endpointDispatcher in channelDispatcher.Endpoints)
                {
                    if (endpointDispatcher.IsSystemEndpoint) continue;
                    DispatchRuntime runtime = endpointDispatcher.DispatchRuntime;
                    runtime.ValidateMustUnderstand = false;
                }
            }
        }
    }
}
```

Then apply this attribute to your service and it will do the same thing. If you are setting other things through the ServiceBehaviorAttribute, you can still apply that attribute.

**Comment by mikhaylo1** [comment] 2024-05-08 14:46
Thank you for providing the options. I think I can use one of them. 
I do not exactly remember, but I believe I have ValidateMustUnderstand = false in the service to support "broken" clients that may include a MustUnderstand=true header but still provide an partially incorrect envelope.

This setting could be particularly relevant if the service functions as the server side of a protocol implementation, where various third-party clients implement the client side using different technology stacks. These clients may not always be fully correct in their envelope and headers structure (according to the protocol specification). Despite these discrepancies, the service still aims to process and understand their requests.

**Comment by mconnew** [comment] 2024-05-08 18:36
If it's to work around broken clients, I'm not a fan of having first class API support for that situation. It encourages doing really bad things like accepting secured signed messages without validating the signature/credentials without putting much thought into it. It also can hide things like configuring your binding to use the wrong version of a SOAP protocol. It really should only be done when you've double and triple checked that you've configured everything correctly.  

Accepting messages with headers that aren't understood should require a very intentional (but not egregiously complicated) step as a small barrier to have someone question are they doing the correct thing. The attribute/behavior I provided further up does the job, requires a change more intentional than simply setting a property, but doesn't add an ongoing code maintenance hardship to your project due to it being reasonably self-documenting and trivial code.  

I'm comfortable with not adding the property to ServiceBehavior for this scenario. Feel free to push back if you disagree though, there might be an aspect I haven't considered.

**Comment by mconnew** [comment] 2024-05-09 16:18
Closing as I believe the issue is resolved

**Closed by mconnew** 2024-05-09 16:18 UTC
