### ISSUE TITLE
Race condition in ConcurrencyInstanceContextFacet class

### ISSUE THREAD

**Issue by SergeiPavlov** [CoreWCF/CoreWCF#122] opened 2020-04-07 04:17 UTC
There is a race condition:
Function `ConcurrencyInstanceContextFacet.EnqueueNewMessage()` may be called concurrently when 2 WCF requests are processed simultaneously.
https://github.com/CoreWCF/CoreWCF/blob/81cd42c0122bded56cb658ed99ede7efedb10679/src/CoreWCF.Primitives/src/CoreWCF/Dispatcher/ConcurrencyBehavior.cs#L278

As consequence `DequeueWaiter()` fails with `NullReferenceException` and leaves CoreWCF in Faulted state. We have following stack trace:
```
CoreWCF.Dispatcher.ConcurrencyInstanceContextFacet.DequeueWaiter()
CoreWCF.Dispatcher.ConcurrencyBehavior.UnlockInstance(InstanceContext instanceContext)  
CoreWCF.Dispatcher.ImmutableDispatchRuntime.ProcessMessageCleanup(MessageRpc rpc)
```

 All subsequent requests return HTTP status 500 with following exception in log:
```
CoreWCF.CommunicationObjectFaultedException:The communication object, CoreWCF.InstanceContext, cannot be used for communication because it is in the Faulted state.
```
Solution: use `ConcurrentQueue<>` instead of thread-unsafe `Queue<>`  in the class `ConcurrencyInstanceContextFacet` and create queue instances at construction time.

**Comment by birojnayak** [comment] 2020-12-22 19:53
@SergeiPavlov I believe the fix placed here https://github.com/CoreWCF/CoreWCF/commit/a81dcea5ffbc2c36beb9be3bc2e0483209356f91 is going to fix the root cause. We are not awaiting once the resource is locked, so eventually queuing would happen one at a time ...

**Comment by mconnew** [comment] 2021-01-08 21:52
@SergeiPavlov, the concurrent collections are a really interesting thing to understand as they are often not the best solution. I've had very senior software engineers (more senior than me) incorrectly suggest a similar thing so you're in good company for not being aware of this. A good article to read on the subject can be [found here](https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/when-to-use-a-thread-safe-collection). I'll quote a couple of the key exerts relevant to this, emphasis added be me:

> In some scenarios, synchronization overhead is negligible and enables the multi-threaded type to perform significantly faster and scale far better than its non-thread-safe equivalent when protected by an external lock. In other scenarios, **_the overhead can cause the thread-safe type to perform and scale about the same or even more slowly_** than the externally-locked, non-thread-safe version of the type.

>  ConcurrentQueue\<T\> **_performs best when one dedicated thread is queuing and one dedicated thread is de-queuing_**. If you do not enforce this rule, then **Queue\<T\> might even perform slightly faster than ConcurrentQueue\<T\>** on computers that have multiple cores.

Basically fixing the locks on the existing queue will perform better than using ConcurrentQueue\<T\> as everything is async and which underlying thread is going to switch a lot. And the more load you have on the system, the more random it will be as to which thread is accessing the queue.

The change that Biroj pointed was intended to fix a race condition where ConcurrencyInstanceContextFacet.HasWaiters being called under lock would return false because newMessageQueue was null, but another thread not under lock was creating a queue and setting newMessageQueue which would mean missing a new message. I didn't see the failure mode that you saw, but it's certainly was possible to instead have a concurrent enqueue and dequeue from the queue which could result in a corrupted state of the queue resulting in what you're seeing. I'm going to close this issue, but reopen it if you are still seeing the problem using the latest build. I don't think I pushed that change up to nuget, so you would need to use the devops package version to validate. If you need this pushed to nuget, let me know and I can do that.

**Closed by mconnew** 2021-01-08 21:52 UTC

**Comment by SergeiPavlov** [comment] 2021-01-12 05:27
@mconnew, Thank you for explanation. I'm agree that `ConcurrentQueue` is not perfect solution for performance. Some lock-less queue may be.
My suggestion to use ConcurrentXXX classes is just ideomatic, to keep the code simple and thread-safe.
Anyway I'm glad that the issue was solved.
