### ISSUE TITLE
ICallContextInitializer is internal

### ISSUE THREAD

**Issue by cyanite** [CoreWCF/CoreWCF#513] opened 2021-12-08 09:34 UTC
ICallContextInitializer and the related properties to set them, are internal.

I am working on a pretty large project with a lot of legacy code, and we decided to try to port our server-side WCF to CoreWCF, while porting to .NET 5 (eventually 6). We use ICallContextInitializer to set up some AsyncLocal state coming from the client, on the server side.

Now, it's most likely possible to make a work-around using a hook point "close" to ICallContextInitializer, such as a message inspector (earlier) or parameter inspector (later), but it would be great if we could use this one.

As far as I could glance from the code, nothing is ever adding call context initializers, so I assume the code using them (which exists) is untested. If you agree that it should be made public, how would that proceed? Would you prefer a PR to that effect, which also adds some tests (if I can figure that out)?

**Comment by dioptryk** [comment] 2021-12-08 09:51
Thumbs up, we need this also.

**Comment by mconnew** [comment] 2021-12-15 18:58
Closing as duplicate of #496

**Closed by mconnew** 2021-12-15 18:58 UTC
