### ISSUE TITLE
Flow of AsyncLocal<T> is broken in CoreWCF pipeline when the operation raises exception or fault

### ISSUE THREAD

**Issue by WenningQiu** [CoreWCF/CoreWCF#487] opened 2021-10-29 14:49 UTC
The flow of `AsyncLocal<T>` in CoreWCF pipeline works fine in normal situations, but is broken when the called service operation raises exception or fault.

```
public sealed class CustomServiceBehavior : IDispatchMessageInspector
{
       private AsyncLocal<int> _asyncLocal = new ();

       object IDispatchMessageInspector.AfterReceiveRequest(ref Message request, IClientChannel channel, InstanceContext instanceContext)
        {
            _asyncLocal.Value = 9999;
        }

        void IDispatchMessageInspector.BeforeSendReply(ref Message reply, object correlationState)
        {
            // _asyncLocal.Value has value 9999 here if the called service operation does not raise exception or fault; otherwise the value is lost.
            var xxx = _asyncLocal.Value;
        }
}
```

This bug may cause trouble to applications that use 3rd-party libraries which may be relying on `AsyncLocal<T>`. The good news is that most applications can use OperationContext to store data related to the operation.

**Comment by mconnew** [comment] 2021-11-11 17:31
These aren't async methods so it doesn't make an effort to flow values through. You can return correlated state in the AfterReceiveRequest method and it gets passed as a parameter to BeforeSendReply. You can do this:
```c#
public sealed class CustomServiceBehavior : IDispatchMessageInspector
{
       object IDispatchMessageInspector.AfterReceiveRequest(ref Message request, IClientChannel channel, InstanceContext instanceContext)
        {
            return 9999;
        }

        void IDispatchMessageInspector.BeforeSendReply(ref Message reply, object correlationState)
        {
            var xxx = (int)correlationState;
        }
}
```

**Comment by mconnew** [comment] 2021-11-11 17:31
Closing as I believe this solves your problem. Feel free to reopen if that's not the case.

**Closed by mconnew** 2021-11-11 17:31 UTC

**Comment by WenningQiu** [comment] 2021-11-12 16:59
I disagree @mconnew. 

I understand that there are other ways to tunnel correlation objects, but that does not justify breaking the flow of AsyncLocal<T> objects. Using other mechanisms may not be an options when third-party assemblies depend on AsyncLocal<T>.

**Comment by BradBarnich** [comment] 2021-11-12 18:52
does this work on full framework WCF? I expect not, because there is not guarantee of being on the same thread context, which is why you are given the state object as part of the api.

**Comment by WenningQiu** [comment] 2021-11-15 03:09
@BradBarnich It works on WCF (.NET Framework). 

In fact our applications have to use `AsyncLocal<T>` on WCF since the service operations await on async methods, in which case WCF OperationContext becomes broken. CoreWCF behaves the opposite way - the OperationContext flows with async methods, but `AsyncLocal<T>` is broken when exception or fault is raised.

Our applications have no problem choosing the appropriate mechanism depending on the target platform since the state objects are fully under our control; but there might be issue for applications that use 3rd-party libraries which depend on `AsyncLocall<T>`.

**Comment by mconnew** [comment] 2021-11-16 01:39
@WenningQiu, things are a lot more complicated and limited with AsyncLocal than they appear on the surface. But before I get into that, you can enable OperationContext async flowing in WCF, but it breaks at least one scenario so it's a "use at your own risk" type of switch. I've done as much due diligence as I can to see if there are other scenarios and couldn't find them, but I can't say 100% there aren't other issues. The only known break is when the service concurrency mode is set to reentrant, a client call will deadlock. It's possible there's other broken scenarios, but that's the only one that was ever reported. If you set the following in your app/web config it will enable flowing of the OperationContext in .NET Framework WCF.
```xml
<appSettings>
    <add key="wcf:disableOperationContextAsyncFlow" value="false"/>
</appSettings>
```

Now back to AsyncLocal's. It doesn't work to flow data to callers of an async method. If an async method updates an AsyncLocal, it's callees will see the updated value, but it's callers won't. The correct place to store stuff between multiple method calls is in an instance method of the class that needs to maintain state. The problem is due to the mechanism used to store the data in an AsyncLocal. It stores it in the current ExecutionContext which uses a copy on write mechanism. In an async method, the current ExecutionContext is captured in the async state machine that's created behind the scenes by the compiler. If the ExecutionContext is replaced due to an AsyncLocal update (copy on write replaces the existing ExecutionContext and leaves the original instance unaltered) in an async method, it gets updated in the async state machine and not in the callers context, leaving the original instance unmodified. This means when the awaiting caller continues, it doesn't see the changes made to the inner ExecutionContext and the original ExecutionContext is used. It might be easiest to demonstrate with an example.

```c#
// .NET 6 console app without a Program class
AsynchronousGadget ag = new AsynchronousGadget();
await ag.DoSomeStuff(false);
Console.WriteLine($"ag.AsyncObject is{(ag.AsyncObject == null ? string.Empty : " not")} null");
await ag.DoSomeStuff(true);
Console.WriteLine($"ag.AsyncObject is{(ag.AsyncObject == null ? string.Empty : " not")} null");

public class AsynchronousGadget
{
    private static AsyncLocal<object> s_asyncObjectHolder = new AsyncLocal<object>();
    public Task DoSomeStuff(bool setBeforeAsync)
    {
        object setObj = new object();
        if (setBeforeAsync)
            s_asyncObjectHolder.Value = setObj;
        return DoSomeStuffImpl(setObj);
    }
    private async Task DoSomeStuffImpl(object obj)
    {
        s_asyncObjectHolder.Value = obj;
        await DoSomeInnerStuff();
        if (ReferenceEquals(s_asyncObjectHolder.Value, obj))
            Console.WriteLine("AsyncLocal unchanged");
    }
    private async Task DoSomeInnerStuff()
    {
        await Task.Yield(); // Simulate doing some real async work
        s_asyncObjectHolder.Value = new object();
    }

    public object? AsyncObject => s_asyncObjectHolder.Value;
}
```
The output from running this code is the following:
```
AsyncLocal unchanged
ag.AsyncObject is null
AsyncLocal unchanged
ag.AsyncObject is not null
```
The `AsyncLocal unchanged` is being output because when DoSomeInnerStuff is called, it copies the current ExecutionContext (with the existing value set in the AsyncLocal) into the async state machine. When the value in the AsyncLocal is updated with a new instance of an object, a new ExecutionContext is created (from copy on write mechanism) and replaces the original one in the async state machine for DoSomeInnerStuff, but the ExecutionContext in DoSomeStuffImpl is unmodified. This means when DoSomeInnerStuff completes and execution continues in DoSomeStuffImpl, the ExecutionContext doesn't contain the updated value for the AsyncLocal and the changes are lost. As you can see, an AsyncLocal is really only useful for passing forwards to callees a value which flows with the async continuations, it's not useful for updating values backwards for callers to see changes reflected.  

I also added to this little sample another demonstration of the behavior. The first time DoSomeStuff is called, setBeforeAsync is false. This means the AsyncLocal doesn't get set until entering the async method DoSomeStuffImpl. This means the main method doesn't see the change reflected and ag.AsyncObject is null after DoSomeStuff completes. When setBeforeAsync is true, the DoSomeStuff method is the one to set the AsyncLocal. As this method is NOT async, there's no implicit state machine created that holds the ExecutionContext, so the same context is being used as the caller. This means the value set in the AsyncLocal is seen by the caller as you haven't entered a new Task context when making the change.  

I hope now that you can see that it doesn't make sense for a 3rd party library to try and flow data between two different method calls via an AsyncLocal as even if they do the same trick of updating the AsyncLocal in a non async Task returning method like I did, they should have no expectation of having the same ExecutionContext being present between method calls. All it would take is for the caller of the 2 methods to be in different async methods (or different calls into the same async method) to cause the AsyncLocal changes to be lost.  

Any fixes I make to use the same ExecutionContext between AfterReceiveRequest and BeforeSendReply would be fragile from 2 perspectives. The "fix" in CoreWCF would be fragile as it takes quite a bit of hackery to achieve and places the code into the realm of what I call "voodoo" code, that is code which is doing something super non-obvious and requires a really deep understanding of that area of code to make changes. I have tried to minimize that type of code in CoreWCF to a minimum to make working on and understanding the code as accessible as possible to outside contributors (WCF on .NET Framework has LOTS of that type of code and is painful to work on). This means it would be easy for someone else to break making some "simple" changes to the dispatcher. It would also be fragile as your own code would only work if you use the non-async Task returning pattern, which makes your own code fragile too. It would be easy for you to break the flowing of AsyncLocal.  

I do completely understand the usefulness of having async support in message inspectors. If you take a [look at this library](https://github.com/mconnew/capri) that I wrote for WCF (I intended to add more and hopefully will, it's designed to just make WCF easier), you can see an improved model for message inspectors. It's not properly async as it builds on top of the existing IClientMessageInspector, but a built in implementation like that in CoreWCF wouldn't have that limitation. This would allow AsyncLocal to flow between the before and after code as they would all be in a single method. Once we get past the 1.0 milestone, I want to spend some time enabling async programming models in all the extensibility points. Until then, returning a correlation object is the correct way to pass values between the two methods because fundamentally you can't pass AsyncLocal values backwards in a call stack and that's what you're asking for.  

The Capri code is MIT licensed so you are free to grab the implementation. There's an implementation built for IDispatchMessageInspector that only gets included when building for NetFx, but should only need a few namespace changes and you can recompile. If you want to submit a PR to that package to enable use on CoreWCF, I'd happily accept it. It might take me a couple of weeks to publish to nuget as I think I need to renew my code signing certifcate. Otherwise feel free to just pull the code into your own project. Just remember you will be blocking a thread on any await's before or after await-ing the next() method as it isn't truly async. It just allows use of the async await pattern to have a single method implement both halfs of the message inspector.

**Comment by WenningQiu** [comment] 2021-11-17 23:26
@mconnew Thanks for explaining the implementation details. I have noticed and understand the one-way (from caller to callee) flowing characteristic of `AsyncLocal<T>` objects, however I still feel fuzzy about if/how it applies to this particular issue regarding CoreWCF pipeline.

In the example that I originally posted, the value (9999) set in AfterReceiveRequest() is still retained and visible in BeforeSendReply() in normal cases even when the service makes calls to async methods, which indicates that no matter what ExecutionContext changes it might have gone through, `_asyncLocal` variable flows as expected. So the two methods are good in terms of caller-callee relationship. 

The flow of `AsyncLocal<T>` is only broken when the service throws an exception or fault, perhaps the exception/fault handling logic in CoreWCF needs to be looked at to find out if/how it might have interfered with the ExecutionContext.

```
public sealed class CustomServiceBehavior : IDispatchMessageInspector
{
       private AsyncLocal<int> _asyncLocal = new ();

       object IDispatchMessageInspector.AfterReceiveRequest(ref Message request, IClientChannel channel, InstanceContext instanceContext)
        {
            _asyncLocal.Value = 9999;
        }

        void IDispatchMessageInspector.BeforeSendReply(ref Message reply, object correlationState)
        {
            // _asyncLocal.Value has value 9999 here if the called service operation does not raise exception or fault; otherwise the value is lost.
            var xxx = _asyncLocal.Value;
        }
}
```

**Comment by mconnew** [comment] 2021-11-18 00:41
An exception is caught one method higher in the callstack. So semantically it would look like this (the code is a lot more involved, but this is representative):
```c#
internal class ImmutableDispatchRuntime
{
    public async Task HandleRequest(Message request)
    {
        try
        {
            await ProcessRequestAsync(request);
        }
        catch(Exception e)
        {
            await ProcessErrorAsync(e);
        }
    }

    public async Task ProcessRequestAsync(Message request)
    {
        CallAfterReceiveMessageInspectors(request);
        object result = await DispatchRequestAsync();
        Message reply = FormatReply(result);
        reply = CallBeforeSendReplyMessageInspectors(reply);
        await SendReplyAsync(reply);
    }

    public async Task ProcessErrorAsync(e)
    {
        Message reply = CreateFaultMessage(e);
        reply = CallBeforeSendReplyMessageInspectors(reply);
        await SendReplyAsync(reply);
    }
}
```
When you don't have an exception, the call to CallAfterReceiveMessageInspectors in ProecessRequestAsync as in the same ExecutionContext scope as CallBeforeSendReplyMessageInspectors. Any changes made in CallAfterReceiveMessageInspectors are visible in ProcessRequestAsync as CallAfterReceiveMessageInspectors isn't an async method. This then means any changes to the AsyncLocal are visible in CallBeforeSendReplyMessageInspectors. When an exception happens, any changes to an AsyncLocal after enterring the ProcessRequestAsync method get effectively unwound and are not visible in HandleRequest. So when ProcessErrorAsync is called, any changes made in CallAfterReceiveMessageInspectors is undone.  

There are other areas where things can get interesting. If you capture a synchronization context and dispatch your operations using that, an AsyncLocal change can persist between the two message inspector methods, but not be reflected in your service call which happens between them. As I mentioned before, an AsyncLocal isn't an appropriate storage mechanism to pass things backwards, or even sideways (which is your intention). It's for a caller to pass ambient state to a callee. Any code which sets an AsyncLocal should only be doing so with the intention that it will be available to child call stacks. Any library attempting to use it for passing values backwards (which is the scenario you are wanting) is going to be fragile.  

I could make this work with some significant refactoring but that would be a bad idea., It would be fragile to code changes and would then get in the way of future improvements to the code as it would enforce a flat single method to do everything. Right now the ImmutableDispatchRuntime is a large number of methods from the .NET Framework implementation basically put into a small number of Async methods as it was the fastest way to get it working correctly using Task's. The previous implementation was a super complicated APM based async state machine. When I get time, I'd like to refactor that entire class and have it built more like asp.net core middleware where it's pieces chained together. There's some excess per dispatch allocations I'd like to get rid of which this would help with. 

I hope that helps answer your question. One final idea I've had, and that's capture the ExecutionContext (`ExecutionContext.Capture()`) at the end of AfterReceiveRequest, and use `ExecutionContext.Run` in BeforeSendReply. So something like this:
```c#
public sealed class CustomServiceBehavior : IDispatchMessageInspector
{
        private AsyncLocal<int> _asyncLocal = new ();

        object IDispatchMessageInspector.AfterReceiveRequest(ref Message request, IClientChannel channel, InstanceContext instanceContext)
        {
            _asyncLocal.Value = 9999;
            return ExecutionContext.Capture();
        }

        void IDispatchMessageInspector.BeforeSendReply(ref Message reply, object correlationState)
        {
            var wrapper = new MessageRefWrapper { WrappedMessage = reply };
            ExecutionContext.Run(correlationState as ExecutionContext, BeforeSendReplyHelper, wrapper);
            reply = wrapper.WrappedMessage; // Needed if reply is modified by core method
        }

        // This replaces BeforeSendReply and flows the original ExecutionContext.
        private void BeforeSendReplyCore(ref Message reply) // Correlation state not being used, otherwise this wouldn't be needed
        {
            var xxx = _asyncLocal.Value;
        }

        private void BeforeSendReplyHelper(object state)
        {
            MessageRefWrapper wrapper = state as MessageRefWrapper;
            Message message = wrapper.WrappedMessage;
            BeforeSendReplyCore(ref message);
            wrapper.WrappedMessage = message;
        }

        private class MessageRefWrapper
        {
            public Message WrappedMessage { get; set; }
        }
}
```

**Comment by WenningQiu** [comment] 2021-11-18 04:54
That makes sense @mconnew, thanks for the explanation.

I noticed that both CallAfterReceiveMessageInspectors() and CallBeforeSendReplyMessageInspectors() are regular methods. Perhaps it is possible to achieve more consistent behavior by calling them directly from HandleRequest(), instead of wrapping them in async methods ProcessRequestAsync() and ProcessErrorAsync(). The change will require splitting the wrapping async methods into separate ones in the real code, but your semantically simplified code might be tweaked to something like this:

```
internal class ImmutableDispatchRuntime
{
    public async Task HandleRequest(Message request)
    {
        try
        {
            CallAfterReceiveMessageInspectors(request);
            object result = await DispatchRequestAsync();
            Message reply = FormatReply(result);
            reply = CallBeforeSendReplyMessageInspectors(reply);
            await SendReplyAsync(reply);
        }
        catch(Exception e)
        {
            Message resply = CreateFaultMessage(e);
            reply = CallBeforeSendReplyMessageInspectors(reply);
            await SendReplyAsync(reply);
        }
    }
}
```

**Comment by mconnew** [comment] 2021-11-18 05:31
The actual implementation code is a lot more complicated than that. As I mentioned, the code would be fragile to future refactoring. Refactoring the code to support a scenario which works by coincidence in some cases to have it work all the time would be turning this into a supported feature. That's a bad idea as AsyncLocal isn't intended to be used this way and it's encouraging wrong usage patterns.  

There are multiple ways to make data flow between code points. I didn't even mention stashing values into message properties or writing an attachable extension for Instance Context. You might also be able to do what you want with an IOperationInvoker.  

Having supported customers with WCF for over a decade, I have regretted it nearly every time I go down the path of trying to make work what the customer believes is the solution to their problem. It's almost universally better to take a step back and ask what's the underlying problem that you are trying to solve and then coming up with the right solution to the problem. 

It usually backfires trying to help someone fit a square peg into a round hole instead of helping them create a round peg or finding them a square hole. You are trying to fit a square peg into a round hole and insisting that hole be made square instead of looking for an existing square hole. Making AsyncLocal always flow sideways in a call stack is this kind of problem. It's the wrong solution to your problem.
