### ISSUE TITLE
[FeatureRequest] also catch System.SM.FaultException on Server

### ISSUE THREAD

**Issue by 0x53A** [CoreWCF/CoreWCF#121] opened 2020-04-05 21:39 UTC
I had an issue where my custom ``FaultContract`` didn't seem to work, and found that I threw the wrong Exception.

I had forgotten to change it from ``System.ServiceModel.FaultException<T>`` to ``CoreWcf.FaultException<T>``.

It would be great if CoreWCF could work with both.

Note that this is only really relevant for a .net framework server, because on .net core you normally don't have a reference to System.ServiceModel anyway.

**Comment by mconnew** [comment] 2020-12-10 17:49
Duplicate of #103 so closing

**Closed by mconnew** 2020-12-10 17:49 UTC
