### ISSUE TITLE
IWebHostBuilder is Deprecated. Use IHostBuilder instead

### ISSUE THREAD

**Issue by Grauenwolf** [CoreWCF/CoreWCF#347] opened 2021-04-16 21:39 UTC
> IWebHostBuilder remains in 3.0 and is the type of the webBuilder seen in the preceding code sample. WebHostBuilder will be deprecated in a future release and replaced by HostBuilder.

https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#hostbuilder-replaces-webhostbuilder

This affects  `UseNetTcp` and various tests/samples.

**Comment by mconnew** [comment] 2021-05-13 16:28
This is a duplicate of #229 as switching to IHostBuilder will be a part of moving to use the generic host.

**Closed by mconnew** 2021-05-13 16:28 UTC
