### ISSUE TITLE
Exception when passing <To> and <Action> tags in headers

### ISSUE THREAD

**Issue by DobrovAlexey** [CoreWCF/CoreWCF#433] opened 2021-08-30 16:39 UTC
Hi, I am migrating an existing WCF service, to netcoreapp3.1, using CoreWCF. But the incoming request returns an exception due to the `<To>` and `<Action>` headers:
```
An unhandled exception has occurred: Addressing Version 'AddressingNone (http://schemas.microsoft.com/ws/2005/05/addressing/none)' does not support adding WS-Addressing headers.
System.InvalidOperationException: Addressing Version 'AddressingNone (http://schemas.microsoft.com/ws/2005/05/addressing/none)' does not support adding WS-Addressing headers.
```

https://github.com/CoreWCF/CoreWCF/blob/616e81f48169d9c094c4ad12a334616112cdef71/src/CoreWCF.Primitives/src/CoreWCF/Channels/MessageHeaders.cs#L1451-L1457

In the code, when receiving headers, a check is performed, when using MessageVersion.Addressing = AddressingVersion.None, headers with Namespace=AddressingVersion.None should not exist, but why is this so?
Perhaps I somehow misconfigured the CoreWCF service, or is it a problem with the incoming message?

Sample message:
```xml
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <h:AdditionalInfo xmlns:h="http://schemas.sitels.ru/FRS/IL/External/CallbackApi_v2" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
      <h:Pid>853.10263969503</h:Pid>
    </h:AdditionalInfo>
    <h:MessageId xmlns:h="http://schemas.sitels.ru/FRS/IL/External/CallbackApi_v2">{"RequestId":"012ad413-5551-43ce-ba63-6b4298fabcfb","Sender":"Platform","OrderId":"d0cc97a8-d0c2-4219-8ad3-59e96cb74c2f"}</h:MessageId>
    <To a:mustUnderstand="1" xmlns="http://schemas.microsoft.com/ws/2005/05/addressing/none" xmlns:a="http://schemas.xmlsoap.org/soap/envelope/">http://localhost:9392/CallbackService</To>
    <Action a:mustUnderstand="1" xmlns="http://schemas.microsoft.com/ws/2005/05/addressing/none" xmlns:a="http://schemas.xmlsoap.org/soap/envelope/">http://schemas.sitels.ru/FRS/IL/External/CallbackApi_v2/IUniversalCallbackService/UniversalCallback</Action>
  </s:Header>
  <s:Body>
    <UniversalCallback xmlns="http://schemas.sitels.ru/FRS/IL/External/CallbackApi_v2">
      <parameter xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
        <State>Faulted</State>
      </parameter>
    </UniversalCallback>
  </s:Body>
</s:Envelope>
```

Program:

```c#
		static void Main(string[] args)
		{
                  CreateWebHostBuilder(args)
                      .Build()
                      .Run();
		}

		public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
			WebHost.CreateDefaultBuilder(args)
				.UseStartup<Startup>()
				.CaptureStartupErrors(true);
```

Startup:
```c#
		public void ConfigureServices(IServiceCollection services)
		{
			services.AddServiceModelServices();
			services.Configure<KestrelServerOptions>(options => options.AllowSynchronousIO = true);

			services.AddCors(options =>
			{
				options.AddDefaultPolicy(
					builder =>
						builder.AllowAnyHeader()
							.AllowAnyMethod()
							.AllowAnyOrigin());
			});

			services.AddTransient(serviceProvider =>
			{
				var mapper = serviceProvider.GetService<IMapper>();
				var service = new CallbackService(mapper);
				return service;
			});
		}

		public void Configure(IApplicationBuilder app)
		{
			app
				//.UseMiddleware<RemoveSoapHeaderMiddleware>()
				.UseCors()
				.UseRouting()
				.UseServiceModel(builder =>
				{
					builder.AddService<CallbackService>()
						.AddServiceEndpoint<CallbackService, ICallbackService>
							(new BasicHttpBinding(), $"/{nameof(CallbackService)}");
				});
		}
```

I am trying to avoid the given error using the middleware - RemoveSoapHeaderMiddleware and this works:

```c#
	public class RemoveSoapHeaderMiddleware
	{
		private readonly RequestDelegate _next;

		public RemoveSoapHeaderMiddleware(RequestDelegate next)
		{
			_next = next;
		}

		public async Task InvokeAsync(HttpContext context)
		{
			if (context.Request.Path.Value == $"/{nameof(CallbackService)}")
			{
				var originalBody = await new StreamReader(context.Request.Body).ReadToEndAsync();
				if (string.IsNullOrEmpty(originalBody))
				{
					await context.Response.WriteAsync("The body of the message is empty.");
					return;
				}

				var replaceTo = Regex.Replace(originalBody, @"(<To).*(</To>)", "");
				var replaceAction = Regex.Replace(replaceTo, @"(<Action).*(</Action>)", "");

				var requestData = Encoding.UTF8.GetBytes(replaceAction);
				context.Request.Body = new MemoryStream(requestData);
				context.Request.ContentLength = context.Request.Body.Length;
			}
			await _next(context);
		}
	}
```

But it seems to me that using middleware to remove data from the headers of the input message is not correct.
Can CoreWCF be configured to not receive an AddressingNone exception?
Thanks

**Comment by mconnew** [comment] 2021-08-30 22:09
How did you get the XML from the request? Did you get it from a debugger looking at a Message object (or calling ToString() on a Message object) or was it captured as sent over the network? The message you included is an invalid message which is why you are getting an exception. When using BasicHttpBinding, the default is to use MessageVersion.Soap11. This means using the SOAP 1.1 protocol for the envelope, and no addressing. What BasicHttpBinding does is use the path from the first HTTP request line (the part which is similar to `POST /some/url/mysevice HTTP/1.1`) to know where the message was sent `To`. The `Action` is sent in the HTTP header `SOAPAction`. On receiving a message, once the request body has been deserialized into a Message object, the CoreWCF HTTP transport artificially adds the headers To and Action reconstructed from the HTTP request headers so that later layers can use these headers in a general way. 

The exception you are getting is complaining that you are using AddressingMode.None which means the To and Action headers shouldn't exist in the actual SOAP message itself but they were found there. The problem is on the client side, not the service side. My guess is either it's a dummy test client using HttpClient to validate the service, and whatever mechanism was used to generate the test message was done based on the Message object and not what's sent on the wire, or a custom sender was written for some reason which is serializing the Message object instead of leaving WCF to do it, and isn't do the correct fixups needed to send a valid request over HTTP.

**Comment by mconnew** [comment] 2021-09-09 16:47
@DobrovAlexey, as this looks like a client problem and I've described what's happening, I'm going to close this issue. If you need more help with this, feel free to reopen and add any additional information you have.

**Closed by mconnew** 2021-09-09 16:47 UTC
