### ISSUE TITLE
Source code not compiling

### ISSUE THREAD

**Issue by KamranShahid** [CoreWCF/CoreWCF#128] opened 2020-04-17 15:48 UTC
I am trying to download and compile source code. But it is not compiling. anybody can look unto it? @mconnew

**Comment by Treit** [comment] 2020-04-17 19:52
@KamranShahid, what exactly are the errors you are seeing? You did not provide any details.

I just so happen to have a brand new (Windows 10) computer for working remotely, so I just tried to reproduce any build issues with the CoreWCF repo by doing this:

1. Install git from https://git-scm.com/downloads

2. Install the .NET Core 3.1.101 SDK (as that's the version currently used by CoreWCF) from https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.101-windows-x64-installer

3. Install the .NET 4.7.2 targeting pack (since CoreWCF also builds samples that target .NET 4.7.2) from https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net472-developer-pack-offline-installer

4. Reboot

5. git clone https://github.com/CoreWCF/CoreWCF.git

6. cd .\CoreWCF\src

7. dotnet build .\CoreWCFWithSamples.sln

This built successfully (41 warnings, no errors.)

**Comment by KamranShahid** [comment] 2020-04-17 20:39
I have a VS 2019 with Windows 10. And used dozens of projects. I were just downloading from 
https://github.com/CoreWCF/CoreWCF/archive/master.zip which is the link on main page and tried it from git.
Install the .NET 4.7.2 targeting pack .
I am getting following when opening the project

![image](https://user-images.githubusercontent.com/2170442/79612052-58a92d80-8115-11ea-920d-39006c692a67.png)

**Comment by Treit** [comment] 2020-04-17 20:43
What is the output of `dotnet build .\CoreWCFWithSamples.sln` from the command-line?

**Comment by KamranShahid** [comment] 2020-04-17 20:46
Just Saw one thing. I have more latest .net core minor version.
3.1.201

**Comment by Treit** [comment] 2020-04-17 20:51
Get it building from the command line using just the SDK tools first, then troubleshoot any Visual Studio-specific issues. Failure to load in Visual Studio without giving you an obvious error is most likely a problem with Visual Studio, not something that can be addressed in the CoreWCF code itself.

**Comment by KamranShahid** [comment] 2020-04-17 21:00
@Treit  I simply changed the global.json and azure-pipelines.yml with .net core version to 3.1.201 then built started.
Now getting error

![image](https://user-images.githubusercontent.com/2170442/79613598-48df1880-8118-11ea-992b-bfac6b0f26e4.png)

Looks like there is whole CLI/CD is implemented in that branch. just liked to download simple code base of the implementation
But checking

**Comment by Treit** [comment] 2020-04-17 21:04
Try installing the 3.1.101 version of the .NET Core SDK and reverting your changes. It should build fine with 'dotnet build' of the solution file with that version of the SDK installed.

**Comment by KamranShahid** [comment] 2020-04-17 21:13
i were to open the project after minor version change. And even able to compile the project after getting rid of gitversiontask related build item
Main thing i wanted to see is if there is some implementation for starting service in .net core 3.1
But Project NetCoreServer is targeting .net core 2.1
And the NetCoreServer.Startup is not compiling when tried to updrade it to 3.1 as

**Comment by Treit** [comment] 2020-04-17 21:37
If I change NetCoreServer.csproj to this:
    <TargetFramework>netcoreapp3.1</TargetFramework>

it builds fine for me...

**Comment by KamranShahid** [comment] 2020-04-17 21:52
I am able to run the the service via 

 app.UseServiceModel(builder =>
            {
                builder.AddService<JawwalRecieveApi>();
                builder.AddServiceEndpoint<MyService, IMyService>(new BasicHttpBinding(), "http://localhost:44387/basichttp", new System.Uri("http://localhost:44387"));
                //builder.AddServiceEndpoint<EchoService, Contract.IEchoService>(new NetTcpBinding(), "/nettcp");
            });

Any idea how can i browse my service wsdl?

**Comment by Treit** [comment] 2020-04-17 22:23
Generating WSDL from .NET Core is not currently supported, see https://github.com/CoreWCF/CoreWCF/issues/95

**Comment by KamranShahid** [comment] 2020-04-18 07:29
Can i somehow reference this service via WCFTestClient?

**Closed** 2020-12-10 17:52 UTC
